[general]
network_check_url=http://wifi.vivo.com.cn/generate_204
server_check_url=http://cp.cloudflare.com/generate_204
fallback_udp_policy=reject
geo_location_checker=http://ip-api.com/json/?fields=11024,https://github.com/lauyv/rdat/raw/main/js/qx-loc.js
resource_parser_url=https://github.com/lauyv/rdat/raw/main/js/qx-extract.js
dns_exclusion_list=*.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me, *.cmbchina.com
dns_reject_domain_behavior=nxdomain
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
[dns]
;prefer-doh3
no-system
no-ipv6
server=119.29.29.29
server=223.5.5.5
doh-server=https://dns.alidns.com/dns-query
[policy]
[server_remote]
[filter_remote]
https://github.com/lauyv/rdat/raw/rel/reject.quanx, tag=reject, force-policy=reject, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://github.com/lauyv/rdat/raw/rel/loc-cn.quanx, tag=direct, force-policy=direct, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
[rewrite_remote]
https://github.com/lauyv/rdat/raw/rel/ext/wb.quanx, tag=weibo, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://github.com/lauyv/rdat/raw/rel/ext/bili.quanx, tag=bilibili, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
[server_local]
[filter_local]
geoip, cn, direct
geoip, lan, direct
final, proxy
[rewrite_local]
[task_local]
[mitm]
hostname = www.google.cn
passphrase = 
p12 = 
