[general]
network_check_url=http://wifi.vivo.com.cn/generate_204
server_check_url=http://cp.cloudflare.com/generate_204
fallback_udp_policy=reject
geo_location_checker=http://ip-api.com/json/?fields=11024,https://github.com/dmulle12/rules/raw/main/js/qx-loc.js
resource_parser_url=https://github.com/dmulle12/rules/raw/main/js/qx-extract.js
dns_exclusion_list=*.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me, *.cmbchina.com
dns_reject_domain_behavior=nxdomain
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
[dns]
;prefer-doh3
no-system
no-ipv6
server=8.8.8.8
server=8.8.4.4
doh-server=https://dns.google/dns-query
[policy]
[server_remote]
[filter_remote]
https://github.com/dmulle12/rules/raw/rel/reject.quanx, tag=reject, force-policy=reject, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://github.com/dmulle12/rules/raw/rel/microsoft.quanx, tag=Proxy, force-policy=Proxy, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://github.com/dmulle12/rules/raw/rel/streaming-cn.quanx, tag=direct, force-policy=direct, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://github.com/dmulle12/rules/raw/rel/loc-cn.quanx, tag=direct, force-policy=direct, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
[rewrite_remote]
https://github.com/dmulle12/rules/raw/rel/ext/wb.quanx, tag=weibo, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
https://github.com/dmulle12/rules/raw/rel/ext/bili.quanx, tag=bilibili, update-interval=172800, opt-parser=false, inserted-resource=true, enabled=true
[server_local]
[filter_local]
geoip, cn, direct
geoip, lan, direct
final, proxy
[rewrite_local]
[task_local]
event-interaction https://ddgksf2013.top/scripts/server-info-pure.js, tag=节点详情(Pure), img-url=checkmark.shield.fill.system
event-interaction https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js, tag=网络信息 𝕏, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.webp, enabled=false
event-interaction https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/geo_location.js, tag=GeoIP 查询, img-url=location.fill.viewfinder.system, enabled=true
event-interaction https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/streaming-ui-check.js, tag=流媒体解锁查询, img-url=checkmark.seal.system, enabled=true
event-network https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js, tag=网络信息变化 𝕏, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png, enabled=true
event-interaction https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js, tag=网络信息 𝕏, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png, enabled=true
[mitm]
hostname = www.google.cn
passphrase = 
p12 = 
